<template>
  <div>
    <Header1 />
    <v-container>
      <v-row class="portfolio-row mb-20 pt-20">
        <h1 class="text-h1" style="margin-bottom: 10px">{{ title }}</h1>
        <!--desc -->
        <!-- <p v-html="desc"></p> -->
        <v-container style="width: 100%">
          <img
            src="@/assets/images/portfolio/projects/sra.png"
            class="img-fluid about-me-img"
            alt=""
          />
          <p>
            The Yield Estimation System for Sugarcane Project was a project that aimed to help the farmers in the Philippines optimize their sugar production. The Philippines is a major sugar producer, but it faces challenges such as typhoons and other extreme weather conditions that affect the crop yield. The project used crop yield modelling, remote sensing, and digital solutions development to provide the farmers with accurate and timely information on their sugarcane fields.
          </p>
          <p>
            My role in this project was to design a platform that would allow the farmers to access and use the information generated by the project. The platform would show them the estimated crop yield for their area, as well as other relevant data such as soil moisture, crop health, and weather forecast. The platform would also enable them to adjust their farm practices and management based on the data, such as when to harvest, irrigate, fertilize, or replant.
          </p>
          <p>
            What made this project unique was that the specifications for the platform were not pre-determined. I had the freedom and responsibility to explore various user research methodologies and design tools to determine the highest impact features and development prioritization. I conducted interviews, surveys, focus groups, and usability tests with the farmers and other stakeholders to understand their needs, preferences, challenges, and expectations. I also used tools such as personas, user journeys, wireframes, prototypes, and mockups to design and test the platform’s functionality, usability, and aesthetics.
          </p>
        </v-container>
        <!-- <horizontal-scroll style="height: 60%"> -->
          
        <!-- </horizontal-scroll> -->

        <!--social -->

        <!--legend -->
        <!-- loop images -->
      </v-row>
    </v-container>
  </div>
</template>

<script>
import HorizontalScroll from "vue-horizontal-scroll";
import "vue-horizontal-scroll/dist/vue-horizontal-scroll.css";

export default {
  name: "SRAYESS",
  data() {
    return {
        title:"SRA YESS",
        desc:"",
        page:""
    };
  },
  methods: {
    buildImagePath: function (i) {
      return require("@/assets/images/work/toallthewomenoftheworld/dataPortrait_" +
        (i - 1) +
        "_processed.jpg");
    },
  },
  components: {
    Header1: () => import("@/components/header/Header1"),
    Banner1: () => import("@/components/banner/Banner1"),
    HorizontalScroll,
  },
};
</script>
<style lang="scss" scoped>
.portfolio-card {
  border-radius: 0px !important;
  box-shadow: none !important;
}

.portfolio-row {
  margin-top: 20px;
  margin-bottom: 20px;
  width: 100%;
}
</style>